# CONFIG_IMEC_STAGE1_ANCHOR_CONTINUOUS_SCAN is not set
# CONFIG_IMEC_STAGE1_ANCHOR_FOCUSED_RX_LOGS is not set
CONFIG_IMEC_ANCHOR_UWB_SCAN_INTERVAL_MS=380
CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US=5000
# CONFIG_IMEC_STAGE1_ANCHOR_SCAN_ALLOW_OVER_RX_BUDGET is not set
