CONFIG_IMEC_USB_CDC_LOGS=n
CONFIG_IMEC_RTT_LOGS=y
CONFIG_IMEC_GATEWAY_BINARY_CDC=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_CONSOLE=y
