CONFIG_IMEC_HIGH_DEBUG=y
CONFIG_IMEC_RTT_LOGS=y
CONFIG_IMEC_HIGH_DEBUG_COUNTER_PERIOD_MS=30000
CONFIG_IMEC_HIGH_DEBUG_COMMAND_POLL_MS=20

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_THREAD_NAME=y
CONFIG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y

CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_MODE_DEFERRED=y
