CONFIG_IMEC_HIGH_DEBUG=y
CONFIG_IMEC_USB_BOOTLOADER=y
CONFIG_IMEC_USB_CDC_LOGS=y
CONFIG_IMEC_RTT_LOGS=y
CONFIG_IMEC_HIGH_DEBUG_COUNTER_PERIOD_MS=30000
CONFIG_IMEC_HIGH_DEBUG_COMMAND_POLL_MS=20

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
CONFIG_ASSERT=y
CONFIG_REBOOT=y
CONFIG_THREAD_NAME=y
CONFIG_PRINTK=y
CONFIG_USE_SEGGER_RTT=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_PRODUCT="IMEC High Debug"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_DEFERRED=y
