#ifndef MESH_RADIO_TIMING_H
#define MESH_RADIO_TIMING_H

/* Production-candidate connected-routing defaults. */
#define MESH_RADIO_ANCHOR_SCAN_RX_US 3000u
#define MESH_RADIO_ANCHOR_SCAN_RESCHEDULE_MS 380u
#define MESH_RADIO_ACTIVITY_COMPLETION_US 15000u
#define MESH_RADIO_WAKE_TRAIN_MS 400u
#define MESH_RADIO_DISCOVERY_SLOT_US 12000u
#define MESH_RADIO_EVENT_INTERVAL_MS 440u
#define MESH_RADIO_EVENT_WINDOW_MS 120u
#define MESH_RADIO_EVENT_FIRST_DELAY_MS 500u
#define MESH_RADIO_EVENT_ACCEPT_DELAY_MS 80u
#define MESH_RADIO_EVENT_CONTROL_REFERENCE_MS 10u
#define MESH_RADIO_EVENT_GUARD_MS 30u
#define MESH_RADIO_EVENT_TX_OFFSET_MS 15u
#define MESH_RADIO_EVENT_ACCEPT_REALIGN_SLOP_MS 20u
#define MESH_RADIO_EVENT_MAX_MISSES 16u
#define MESH_RADIO_EVENT_SUPERVISION_MS 30000u
#define MESH_RADIO_EVENT_RX_LATE_GUARD_MS 60u
#define MESH_RADIO_WAKE_SNIFF_US 20000u
#define MESH_RADIO_WAKE_POLITENESS_CHECK_US 20000u
#define MESH_RADIO_WAKE_OPPORTUNITIES 4u

#endif
