CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_ENTROPY_GENERATOR=n

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n
CONFIG_THREAD_NAME=n
CONFIG_ASSERT=n
CONFIG_REBOOT=n
CONFIG_POWEROFF=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
