CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_PRINTK=y

CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n
CONFIG_THREAD_NAME=n
CONFIG_ASSERT=n
