#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "app_device_identity.h"
#include "app_mesh_direct_gateway_retry.h"
#include "mesh_capacity.h"
#include "mesh_radio_timing.h"
#include "mesh_relay.h"
#include "status.h"
#include "survey.h"
#include "uwb.h"

#include <zephyr/devicetree.h>
#include <zephyr/kernel.h>

/*
 * App-local build configuration will move here during the mechanical split.
 * Keep this header private to firmware/app/src.
 */

#define ROLE_CLICKER 1
#define ROLE_ANCHOR 2
#define ROLE_GATEWAY 3

#ifndef DEVICE_ROLE
#define DEVICE_ROLE ROLE_CLICKER
#endif

#if defined(CONFIG_IMEC_GATEWAY_BLE_CONNECTIVITY_TEST)
#define BLE_CONNECTIVITY_TEST_UNUSED __attribute__((unused))
#else
#define BLE_CONNECTIVITY_TEST_UNUSED
#endif

#if defined(CONFIG_IMEC_ML_ANCHOR)
#define ML_ANCHOR_ONLY_UNUSED
#else
#define ML_ANCHOR_ONLY_UNUSED __attribute__((unused))
#endif

#if defined(CONFIG_IMEC_ML_CLICKER)
#define ML_CLICKER_BUTTON_UNUSED __attribute__((unused))
#else
#define ML_CLICKER_BUTTON_UNUSED
#endif

#if defined(CONFIG_IMEC_GATEWAY_BLE_CONNECTIVITY_TEST) || \
    defined(CONFIG_IMEC_ML_CLICKER) || \
    defined(CONFIG_IMEC_ML_ANCHOR) || \
    defined(CONFIG_IMEC_MESH_ROUTE_TEST) || \
    !defined(CONFIG_IMEC_GATEWAY_BLE)
#define GATEWAY_BLE_HOST_COMMAND_UNUSED __attribute__((unused))
#else
#define GATEWAY_BLE_HOST_COMMAND_UNUSED
#endif

#if defined(CONFIG_IMEC_STAGE1_TAG_CONTINUOUS_WAKE_CLAIMS)
#define STAGE1_WAKE_SPAM_UNUSED __attribute__((unused))
#else
#define STAGE1_WAKE_SPAM_UNUSED
#endif

#ifndef GATEWAY_ID
#define GATEWAY_ID 0x9999888877776666ull
#endif

#ifndef DEVICE_ID
#if IMEC_USE_HARDWARE_ANCHOR_ID
#define DEVICE_ID app_device_id()
#elif DEVICE_ROLE == ROLE_ANCHOR
#define DEVICE_ID 0x2222222222222222ull
#elif DEVICE_ROLE == ROLE_GATEWAY
#define DEVICE_ID GATEWAY_ID
#else
#define DEVICE_ID 0x1111111111111111ull
#endif
#endif

#ifndef NETWORK_ID
#define NETWORK_ID 0x494D4543u
#endif

#ifndef IMEC_BUILD_PRESET_NAME
#define IMEC_BUILD_PRESET_NAME ""
#endif

#ifndef IMEC_GIT_VERSION
#define IMEC_GIT_VERSION "unknown"
#endif

#ifndef IMEC_BUILD_TIMESTAMP
#define IMEC_BUILD_TIMESTAMP "unknown"
#endif

#ifndef IMEC_BOARD_TARGET
#define IMEC_BOARD_TARGET "unknown"
#endif

#if defined(CONFIG_IMEC_HIGH_DEBUG)
#define IMEC_STAGE CONFIG_IMEC_BENCH_STAGE
#else
#define IMEC_STAGE (-1)
#endif

#define CLICK_BUTTON_NODE DT_ALIAS(click_button)
#define STATUS0_RED_NODE DT_ALIAS(status0_red)
#define STATUS0_GREEN_NODE DT_ALIAS(status0_green)
#define STATUS0_BLUE_NODE DT_ALIAS(status0_blue)
#define STATUS1_RED_NODE DT_ALIAS(status1_red)
#define STATUS1_GREEN_NODE DT_ALIAS(status1_green)
#define STATUS1_BLUE_NODE DT_ALIAS(status1_blue)
#define BATTERY_ADC_ENABLE_NODE DT_ALIAS(battery_adc_enable)
#define BATTERY_ADC_NODE DT_NODELABEL(battery_adc)
#define CLICK_BUTTON_RELEASE_POLL_MS 5u
#define CLICK_BUTTON_RELEASE_STABLE_MS BUTTON_DEBOUNCE_MS
#define CLICKER_ACTION_WORKQUEUE_STACK_SIZE 8192u
#define CLICKER_ACTION_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#define BLE_COURTESY_ADV_INTERVAL_MIN_UNITS 0x0020u
#define BLE_COURTESY_ADV_INTERVAL_MAX_UNITS 0x0021u
#define BLE_COURTESY_SCAN_INTERVAL_UNITS 40u
#define BLE_COURTESY_SCAN_WINDOW_UNITS 32u

#define UWB_DISCOVERY_SLOT_US MESH_RADIO_DISCOVERY_SLOT_US
#define UWB_POST_BURST_DIAG_GUARD_MS 120u
#define UWB_POST_BURST_DIAG_SLOT_MS 1000u
#define GATEWAY_BLE_RX_FRAME_QUEUE_DEPTH 4u
#define GATEWAY_BLE_DIRECT_TX_QUEUE_DEPTH 2u
#define GATEWAY_BLE_DEFAULT_NOTIFY_CHUNK 20u
#define GATEWAY_BLE_TX_RETRY_MS 2u
#define GATEWAY_BLE_TX_RETRY_MAX_MS 128u

#define MAX_SCHEDULED_ANCHORS UWB_RANGE_SCHEDULE_MAX_ANCHORS
#define MAX_SUCCESSFUL_ANCHORS 16u
#define WAKE_ADV_MS MESH_RADIO_WAKE_TRAIN_MS
#define ANCHOR_UWB_WAIT_MS 500u
#define UWB_DISCOVERY_RX_GUARD_MS 8u
#define UWB_DISCOVERY_RX_LATE_GUARD_MS 100u
#define UWB_DISCOVERY_LISTEN_MS \
    (UWB_DISCOVERY_RX_GUARD_MS + UWB_DISCOVERY_RX_LATE_GUARD_MS)
#define UWB_DISCOVERY_REPLY_TX_TIMEOUT_MS 20u
#define UWB_CONTROL_TX_TIMEOUT_MS 20u
#define UWB_RANGE_SCHEDULE_RX_MS 80u
#define UWB_SCHEDULE_GUARD_MS 10u
#define MESH_ROUTE_TEST_WAKE_TO_ROUTE_DELAY_MS 40u
#define MESH_CONTROL_FOLLOWUP_TURNAROUND_MS \
    MESH_ROUTE_TEST_WAKE_TO_ROUTE_DELAY_MS
#define MESH_ROUTE_TEST_REPLY_WINDOW_GUARD_MS 250u
#define MESH_ROUTE_TEST_POST_WAKE_ROUTE_RX_MS 1250u
#define UWB_WAKE_CHANNEL UWB_CHANNEL_WAKE_CONTACT
#define UWB_RANGING_CHANNEL UWB_CHANNEL_WAKE_CONTACT
#define UWB_RANGE_FIRST_POLL_DELAY_MS 50u
#define UWB_SAMPLES_PER_ANCHOR 2u
#define UWB_MAX_DISCOVERY_WINDOW_MS \
    (((MAX_SCHEDULED_ANCHORS * UWB_DISCOVERY_SLOT_US) + 999u) / 1000u)
#define UWB_CLICKER_MAX_SAMPLES_PER_ANCHOR UWB_RANGING_REQUESTS_MAX_PER_ANCHOR
#define UWB_SCHEDULED_RANGE_SPAN_MS \
    (UWB_RANGE_FIRST_POLL_DELAY_MS + UWB_RANGE_SCHEDULE_DEFAULT_BURST_WINDOW_MS + \
     UWB_SCHEDULE_GUARD_MS)
#define UWB_POST_WAKE_CLAIMED_DURATION_MS \
    (UWB_MAX_DISCOVERY_WINDOW_MS + UWB_RANGE_SCHEDULE_RX_MS + \
     UWB_SCHEDULED_RANGE_SPAN_MS)
#define UWB_CLICKER_CLAIMED_DURATION_MS \
    (WAKE_ADV_MS + UWB_POST_WAKE_CLAIMED_DURATION_MS)
#define MAX_WAKE_ATTEMPTS 6u
#define UWB_ANCHOR_RANGE_WINDOW_MS UWB_RANGE_SCHEDULE_DEFAULT_BURST_WINDOW_MS
#define UWB_POLITE_SAMPLE_RX_MS 50u
#define UWB_POLITE_REQUIRED_QUIET_SAMPLES 2u
#define UWB_POLITE_RELEVANT_FRAME_WAIT_MS UWB_POST_WAKE_CLAIMED_DURATION_MS
#define MAX_POLITENESS_WAIT_MS 500u
#define UWB_RETRY_BASE_DELAY_MS 150u
#define BLE_COURTESY_MIN_WINDOW_MS 100u
#define BLE_COURTESY_PEER_FINISH_MS \
    (BLE_COURTESY_MIN_WINDOW_MS + UWB_CLICKER_CLAIMED_DURATION_MS)
#define BLE_COURTESY_MAX_DEFERS_PER_ATTEMPT 3u
#define CLICK_REPORT_BUILD_GUARD_MS 20u
#define CLICK_UWB_TIMEOUT_MS 40u
#define CLICK_REPORT_DEADLINE_MS 15000u
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define ANCHOR_UWB_SCAN_INTERVAL_MS CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_INTERVAL_MS
#define ANCHOR_UWB_SCAN_RX_US CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_RX_US
#define ANCHOR_UWB_SCAN_RX_MS ((CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_RX_US + 999u) / 1000u)
#define ANCHOR_STAGE1_FOCUSED_RX_SPIN_MS 0u
#elif IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
#define ANCHOR_UWB_SCAN_INTERVAL_MS 0u
#define ANCHOR_UWB_SCAN_RX_US 20000u
#define ANCHOR_UWB_SCAN_RX_MS 20u
#define ANCHOR_STAGE1_FOCUSED_RX_SPIN_MS 0u
#elif IS_ENABLED(CONFIG_IMEC_STAGE1_ANCHOR_CONTINUOUS_SCAN)
#define ANCHOR_UWB_SCAN_INTERVAL_MS 317u
#define ANCHOR_UWB_SCAN_RX_US 80000u
#define ANCHOR_UWB_SCAN_RX_MS 80u
#define ANCHOR_STAGE1_FOCUSED_RX_SPIN_MS 0u
#elif IS_ENABLED(CONFIG_IMEC_STAGE1_ANCHOR_SCAN_ALLOW_OVER_RX_BUDGET)
#define ANCHOR_UWB_SCAN_INTERVAL_MS CONFIG_IMEC_ANCHOR_UWB_SCAN_INTERVAL_MS
#define ANCHOR_UWB_SCAN_RX_US CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US
#define ANCHOR_UWB_SCAN_RX_MS ((CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US + 999u) / 1000u)
#define ANCHOR_STAGE1_FOCUSED_RX_SPIN_MS 0u
#else
#define ANCHOR_UWB_SCAN_INTERVAL_MS CONFIG_IMEC_ANCHOR_UWB_SCAN_INTERVAL_MS
#define ANCHOR_UWB_SCAN_RX_US CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US
#define ANCHOR_UWB_SCAN_RX_MS ((CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US + 999u) / 1000u)
#define ANCHOR_STAGE1_FOCUSED_RX_SPIN_MS 0u
#endif
#define ANCHOR_UWB_STARTUP_US 2500u
#define ANCHOR_UWB_PLL_US 170u
#define ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S 13000u
#define ANCHOR_UWB_IDLE_SCAN_DUTY_US ANCHOR_UWB_SCAN_RX_US
#define ANCHOR_UWB_IDLE_SCAN_AWAKE_US \
    (ANCHOR_UWB_STARTUP_US + ANCHOR_UWB_PLL_US + ANCHOR_UWB_SCAN_RX_US)
#define ANCHOR_UWB_IDLE_SCAN_PERIOD_US \
    ((ANCHOR_UWB_SCAN_INTERVAL_MS * 1000u) + ANCHOR_UWB_IDLE_SCAN_AWAKE_US)
#define ANCHOR_UWB_IDLE_SCAN_RX_OFF_GAP_US \
    ((ANCHOR_UWB_SCAN_INTERVAL_MS * 1000u) + ANCHOR_UWB_STARTUP_US + \
     ANCHOR_UWB_PLL_US)
#define ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS 60000u
#define ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS \
    ((((uint64_t)WAKE_ADV_MS * 1000ull) - ANCHOR_UWB_STARTUP_US - \
      ANCHOR_UWB_PLL_US - 1ull) / 1000ull)
#define ANCHOR_UWB_SCAN_MAX_INTERVAL_MS \
    (ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS < \
     ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS ? \
     ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS : \
     ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS)
#define ANCHOR_CLAIM_COLLECTION_MS 15u
#define ANCHOR_FALSE_WAKE_COOLDOWN_MS 100u
#define ANCHOR_UWB_SCAN_ACTIVITY_COMPLETION_MS 15u
#define ANCHOR_UWB_SCAN_ACTIVITY_MIN_COMPLETION_MS 8u
#define ANCHOR_UWB_SCAN_POST_SEQUENCE_IDLE_MS 25u
#define ANCHOR_UWB_SCAN_BUSY_RETRY_MS 5u
#define ANCHOR_UWB_SCAN_MESH_RX_RETRY_MS 20u
#define ANCHOR_UWB_SCAN_DEFERRED_MESH_RX_GAP_MS 250u
#define ANCHOR_SCHEDULE_NO_POLL_GUARD_MS 5000u
#define ANCHOR_HEARTBEAT_DEFAULT_INTERVAL_MS 60000u
#define ANCHOR_HEARTBEAT_MIN_INTERVAL_MS 5000u
#define ANCHOR_HEARTBEAT_MAX_INTERVAL_MS 3600000u
#define ANCHOR_REBOOT_RESULT_DRAIN_MS 100u
#define ANCHOR_REBOOT_RESULT_POLL_MS 50u
#define ANCHOR_REBOOT_RESULT_MAX_WAIT_MS (GATEWAY_COMMAND_RESULT_TIMEOUT_MS + 500u)
#define UWB_MESH_ANCHOR_RX_INTERVAL_MS 6000u
#define UWB_MESH_ANCHOR_RX_WINDOW_MS 2u
#define ANCHOR_UWB_SCAN_MIN_INTERVAL_MS \
    ((((uint64_t)ANCHOR_UWB_IDLE_SCAN_DUTY_US * 1000000ull + \
       ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S - 1ull) / \
      ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S - \
      ANCHOR_UWB_IDLE_SCAN_DUTY_US + 999ull) / 1000ull)
#define ANCHOR_UWB_SCAN_RX_US_PER_S \
    (((uint64_t)ANCHOR_UWB_IDLE_SCAN_DUTY_US * 1000000ull + \
      ANCHOR_UWB_IDLE_SCAN_PERIOD_US - 1ull) / ANCHOR_UWB_IDLE_SCAN_PERIOD_US)
#define ANCHOR_UWB_SCAN_AWAKE_US_PER_S \
    (((uint64_t)ANCHOR_UWB_IDLE_SCAN_AWAKE_US * 1000000ull + \
      ANCHOR_UWB_IDLE_SCAN_PERIOD_US - 1ull) / ANCHOR_UWB_IDLE_SCAN_PERIOD_US)
#define ANCHOR_UWB_PERIODIC_IDLE_US_PER_S ANCHOR_UWB_SCAN_AWAKE_US_PER_S
#define UWB_MESH_GATEWAY_RX_WINDOW_MS 30000u
#define UWB_MESH_GATEWAY_RX_IDLE_MS 2u
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_EVENT_DEFAULT_INTERVAL_MS MESH_RADIO_EVENT_INTERVAL_MS
#define MESH_EVENT_DEFAULT_WINDOW_MS MESH_RADIO_EVENT_WINDOW_MS
#define MESH_EVENT_DEFAULT_FIRST_DELAY_MS MESH_RADIO_EVENT_FIRST_DELAY_MS
#define MESH_EVENT_DEFAULT_GUARD_MS MESH_RADIO_EVENT_GUARD_MS
#define MESH_EVENT_DEFAULT_SECOND_SLOT_OFFSET_MS (MESH_EVENT_DEFAULT_INTERVAL_MS / 2u)
#define MESH_EVENT_RX_LATE_GUARD_MS MESH_RADIO_EVENT_RX_LATE_GUARD_MS
#else
#define MESH_EVENT_DEFAULT_INTERVAL_MS 80u
#define MESH_EVENT_DEFAULT_WINDOW_MS 12u
#define MESH_EVENT_DEFAULT_FIRST_DELAY_MS 20u
#define MESH_EVENT_DEFAULT_GUARD_MS UWB_SCHEDULE_GUARD_MS
#define MESH_EVENT_DEFAULT_SECOND_SLOT_OFFSET_MS 0u
#define MESH_EVENT_RX_LATE_GUARD_MS 0u
#endif
#define MESH_EVENT_DEFAULT_MAX_MISSED MESH_RADIO_EVENT_MAX_MISSES
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_EVENT_DEFAULT_SUPERVISION_MS MESH_RADIO_EVENT_SUPERVISION_MS
#else
#define MESH_EVENT_DEFAULT_SUPERVISION_MS 1000u
#endif
#if IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
/*
 * ML anchors use the shared channel-5 ranging scanner but never start the
 * connected-mesh RX/report workers.  Retain one fail-closed slot for any
 * unexpected legacy call without reserving production queue capacity.
 */
#define MESH_RX_QUEUE_DEPTH 1
#elif IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_RX_QUEUE_DEPTH 4
#else
#define MESH_RX_QUEUE_DEPTH 8
#endif
#if DEVICE_ROLE == ROLE_ANCHOR && IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
#define REPORT_TX_QUEUE_DEPTH 1
#elif DEVICE_ROLE == ROLE_ANCHOR && IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define REPORT_TX_QUEUE_DEPTH MESH_CONNECTED_ANCHOR_REPORT_QUEUE_CAPACITY
#elif DEVICE_ROLE == ROLE_ANCHOR
#define REPORT_TX_QUEUE_DEPTH 16
#else
#define REPORT_TX_QUEUE_DEPTH 1
#endif
#define REPORT_TX_RETRY_DELAY_MS 1000u
#define UWB_MESH_TX_TIMEOUT_MS 20u
#define ANCHOR_BATTERY_MV_UNKNOWN 0u
#define SURVEY_REACH_MAX_ENTRIES 12u
#define SURVEY_PAIR_SAMPLE_GAP_MS 10u
#define SURVEY_DISCOVERY_START_DELAY_MS 6000u
#define SURVEY_DISCOVERY_PHY_PREP_MEASURED_MAX_MS 63u
#define SURVEY_DISCOVERY_PHY_PREP_MARGIN_MS 40u
#define SURVEY_DISCOVERY_PHY_PREP_BUDGET_MS 103u
BUILD_ASSERT(SURVEY_DISCOVERY_PHY_PREP_BUDGET_MS >=
             SURVEY_DISCOVERY_PHY_PREP_MEASURED_MAX_MS +
             SURVEY_DISCOVERY_PHY_PREP_MARGIN_MS,
             "survey PHY preparation must cover the hardware maximum plus margin");
BUILD_ASSERT(SURVEY_DISCOVERY_START_DELAY_MS >=
             SURVEY_DISCOVERY_PHY_PREP_BUDGET_MS,
             "default survey start delay must allow early PHY preparation");
#define SURVEY_DISCOVERY_SLOT_MS 40u
#define SURVEY_DISCOVERY_DEFAULT_SLOT_COUNT 6u
#define SURVEY_RESULT_MESH_SLOT_MS \
    (ROUTE_GATEWAY_ACK_TIMEOUT_MS + UWB_MESH_TX_TIMEOUT_MS + 250u)
#define SURVEY_DIRECT_GATEWAY_PROBE_ATTEMPT_MS \
    (UWB_MESH_TX_TIMEOUT_MS + APP_MESH_DIRECT_GATEWAY_ACK_GUARD_MS + \
     APP_MESH_DIRECT_GATEWAY_ACK_RX_MS + \
     APP_MESH_DIRECT_GATEWAY_SURVEY_SCRATCH_ACQUIRE_MS + \
     APP_MESH_DIRECT_GATEWAY_SURVEY_TRANSITION_GUARD_MS)
#define SURVEY_DISCOVERY_REPORT_DELIVERY_TAIL_MS \
    APP_MESH_DIRECT_GATEWAY_SURVEY_DELIVERY_TAIL_MS( \
        SURVEY_DIRECT_GATEWAY_PROBE_ATTEMPT_MS, \
        APP_MESH_DIRECT_GATEWAY_SURVEY_SCRATCH_ACQUIRE_MS, \
        MESH_RELAY_GATEWAY_ACK_RETRY_BUDGET_MAX_MS)
BUILD_ASSERT(SURVEY_DISCOVERY_REPORT_DELIVERY_TAIL_MS >
             MESH_RELAY_GATEWAY_ACK_RETRY_BUDGET_MAX_MS,
             "survey delivery tail must include direct-probe and ACK retry horizons");
BUILD_ASSERT(SURVEY_DISCOVERY_REPORT_CUSTODY_MAX_MS <=
             SURVEY_DISCOVERY_REPORT_DELIVERY_TAIL_MS,
             "survey delivery tail must cover maximum hop-aware report custody");
BUILD_ASSERT(SURVEY_MESH_RESULT_OUTBOX_EXPIRY_S * 1000u >=
             SURVEY_DISCOVERY_REPORT_DELIVERY_TAIL_MS,
             "survey outbox expiry must cover direct delivery and ACK repair");
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define ANCHOR_UWB_SCAN_WORKQUEUE_STACK_SIZE 12288u
#else
#define ANCHOR_UWB_SCAN_WORKQUEUE_STACK_SIZE 8192u
#endif
/*
 * Hardware measured 4080 bytes in the restored-survey direct-ACK path.  Keep
 * survey radio work on the existing anchor UWB queue: it already serializes
 * the same DWM3000 and routing paths and has the required safety margin.
 */
#define ANCHOR_SURVEY_WORKQUEUE_HARDWARE_WATERMARK_BYTES 4080u
BUILD_ASSERT(ANCHOR_UWB_SCAN_WORKQUEUE_STACK_SIZE >=
             ANCHOR_SURVEY_WORKQUEUE_HARDWARE_WATERMARK_BYTES + 1024u,
             "anchor survey recovery needs measured stack plus safety margin");
#define ANCHOR_UWB_SCAN_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(1)
#define MESH_TEST_WORKQUEUE_STACK_SIZE 8192u
#define MESH_TEST_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#if IS_ENABLED(CONFIG_IMEC_DEDICATED_COMM_WORKQUEUE)
#if DEVICE_ROLE == ROLE_CLICKER
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 6144u
#elif DEVICE_ROLE == ROLE_GATEWAY
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 8192u
#else
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 9216u
#endif
#define MESH_ROUTE_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#else
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 4096u
#define MESH_ROUTE_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(1)
#endif
#define GATEWAY_SURVEY_AUTO_RETRY_MS 100u
#define ANCHOR_HEARTBEAT_DELIVERY_TIMEOUT_MS 60000u
#define GATEWAY_SURVEY_PAIR_SETTLE_MS 50u
#define GATEWAY_COMMAND_MESH_TIMEOUT_MARGIN_MS 1000u
#define ML_CLICKER_FAST_CACHE_MIN_ANCHORS 4u
#define ML_CLICKER_FAST_CACHE_FRESH_MS 30000u

#define UWB_POST_BURST_DIAG_RX_GUARD_MS 20u
#define UWB_POST_BURST_DIAG_TIMEOUT_MS 250u
#define UWB_POST_BURST_DIAG_ATTEMPTS 3u
#define UWB_POST_BURST_DIAG_RETRY_DELAY_MS 250u
#define UWB_POST_BURST_DIAG_REPLY_DELAY_UUS UWB_RANGE_REPLY_DELAY_UUS
#define UWB_POST_BURST_DIAG_LISTEN_MS \
    (UWB_POST_BURST_DIAG_SLOT_MS + (2u * UWB_POST_BURST_DIAG_RX_GUARD_MS))
#define UWB_POST_BURST_DIAG_ROUND_INDEX 0u
#define UWB_ML_EXCHANGE_STRIDE_US UWB_RANGE_SCHEDULE_MIN_EXCHANGE_STRIDE_US
#define UWB_ML_MAX_SCHEDULED_EXCHANGES \
    (UWB_RANGE_SCHEDULE_MAX_ANCHORS * UWB_RANGING_REQUESTS_MAX_PER_ANCHOR)
#define UWB_ML_MAX_BURST_MS \
    (((UWB_ML_MAX_SCHEDULED_EXCHANGES * UWB_ML_EXCHANGE_STRIDE_US) + 999u) / 1000u)
#define ML_CLICKER_COLLECTION_DEADLINE_MS \
    (WAKE_ADV_MS + UWB_MAX_DISCOVERY_WINDOW_MS + UWB_RANGE_SCHEDULE_RX_MS + \
     UWB_RANGE_FIRST_POLL_DELAY_MS + UWB_ML_MAX_BURST_MS + \
     UWB_POST_BURST_DIAG_GUARD_MS + \
     (UWB_RANGE_SCHEDULE_MAX_ANCHORS * UWB_POST_BURST_DIAG_SLOT_MS) + 5000u)
#define ML_CLICKER_BUFFERED_SAMPLE_MAX UWB_ML_MAX_SCHEDULED_EXCHANGES
#define ML_CLICKER_BUFFERED_FRAME_MAX 1u
#define ML_CLICKER_POST_BURST_DIAG_MAX UWB_RANGE_SCHEDULE_MAX_ANCHORS
#define UWB_FULL_CIR_REPORT_PACKET_BYTES RANGE_REPORT_CIR_PACKET_RAW_MAX_BYTES
#define ML_FULL_CIR_BLE_CHUNK_BYTES 128u
#define ML_DIAG_SOURCE_SUMMARY 0u
#define ML_DIAG_SOURCE_CLICKER 1u
#define ML_DIAG_SOURCE_ANCHOR 2u
#define ML_DIAG_SOURCE_ANCHOR_CIR 3u


#ifndef IMEC_ML_ANCHOR_SLOT
#define IMEC_ML_ANCHOR_SLOT 0u
#endif

#ifndef IMEC_HIGH_DEBUG_ANCHOR_SLOT_ENABLED
#define IMEC_HIGH_DEBUG_ANCHOR_SLOT_ENABLED 0
#endif

#ifndef IMEC_HIGH_DEBUG_ANCHOR_SLOT
#define IMEC_HIGH_DEBUG_ANCHOR_SLOT 0u
#endif

#if IMEC_HIGH_DEBUG_ANCHOR_SLOT_ENABLED
#define ANCHOR_DISCOVERY_SLOT_SOURCE "flashed"
#elif defined(CONFIG_IMEC_ML_ANCHOR)
#define ANCHOR_DISCOVERY_SLOT_SOURCE "ml"
#else
#define ANCHOR_DISCOVERY_SLOT_SOURCE "gateway"
#endif

#endif
