#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "app_device_identity.h"
#include "app_mesh_direct_gateway_retry.h"
#include "device_identity.h"
#include "mesh_capacity.h"
#include "mesh_radio_timing.h"
#include "mesh_relay.h"
#include "operation_policy.h"
#include "status.h"
#include "uwb.h"

#include <zephyr/devicetree.h>
#include <zephyr/kernel.h>

/*
 * App-local build configuration will move here during the mechanical split.
 * Keep this header private to firmware/app/src.
 */

#define ROLE_CLICKER 1
#define ROLE_ANCHOR 2
#define ROLE_GATEWAY 3

#ifndef DEVICE_ROLE
#define DEVICE_ROLE ROLE_CLICKER
#endif

#if defined(CONFIG_IMEC_ML_ANCHOR)
#define ML_ANCHOR_ONLY_UNUSED
#else
#define ML_ANCHOR_ONLY_UNUSED __attribute__((unused))
#endif

#if defined(CONFIG_IMEC_ML_CLICKER)
#define ML_CLICKER_BUTTON_UNUSED __attribute__((unused))
#else
#define ML_CLICKER_BUTTON_UNUSED
#endif

#if defined(CONFIG_IMEC_ML_CLICKER) || \
    defined(CONFIG_IMEC_ML_ANCHOR) || \
     defined(CONFIG_IMEC_MESH_ROUTE_TEST) || \
     !defined(CONFIG_IMEC_GATEWAY_BLE)
#define GATEWAY_BLE_HOST_COMMAND_UNUSED __attribute__((unused))
#else
#define GATEWAY_BLE_HOST_COMMAND_UNUSED
#endif

#define LEGACY_FIXED_CLICKER_ID DEVICE_IDENTITY_LEGACY_FIXED_CLICKER_ID

#ifndef GATEWAY_ID
#define GATEWAY_ID DEVICE_IDENTITY_DEFAULT_GATEWAY_ID
#endif

#ifndef DEVICE_ID
#if IMEC_USE_HARDWARE_DEVICE_ID
#define DEVICE_ID app_device_id()
#elif DEVICE_ROLE == ROLE_ANCHOR
#define DEVICE_ID 0x2222222222222222ull
#elif DEVICE_ROLE == ROLE_GATEWAY
#define DEVICE_ID GATEWAY_ID
#else
#define DEVICE_ID LEGACY_FIXED_CLICKER_ID
#endif
#endif

#ifndef NETWORK_ID
#define NETWORK_ID 0x494D4543u
#endif

#ifndef IMEC_BUILD_PRESET_NAME
#define IMEC_BUILD_PRESET_NAME ""
#endif

#ifndef IMEC_GIT_VERSION
#define IMEC_GIT_VERSION "unknown"
#endif

#ifndef IMEC_BUILD_TIMESTAMP
#define IMEC_BUILD_TIMESTAMP "unknown"
#endif

#ifndef IMEC_BOARD_TARGET
#define IMEC_BOARD_TARGET "unknown"
#endif

#define CLICK_BUTTON_NODE DT_ALIAS(click_button)
#define STATUS0_RED_NODE DT_ALIAS(status0_red)
#define STATUS0_GREEN_NODE DT_ALIAS(status0_green)
#define STATUS0_BLUE_NODE DT_ALIAS(status0_blue)
#define STATUS1_RED_NODE DT_ALIAS(status1_red)
#define STATUS1_GREEN_NODE DT_ALIAS(status1_green)
#define STATUS1_BLUE_NODE DT_ALIAS(status1_blue)
#define BATTERY_ADC_ENABLE_NODE DT_ALIAS(battery_adc_enable)
#define BATTERY_ADC_NODE DT_NODELABEL(battery_adc)
#define CLICK_BUTTON_RELEASE_POLL_MS 5u
#define CLICK_BUTTON_RELEASE_STABLE_MS BUTTON_DEBOUNCE_MS
#define CLICKER_ACTION_WORKQUEUE_STACK_SIZE 8192u
#define CLICKER_ACTION_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#define BLE_COURTESY_ADV_INTERVAL_MIN_UNITS 0x0020u
#define BLE_COURTESY_ADV_INTERVAL_MAX_UNITS 0x0021u
#define BLE_COURTESY_SCAN_INTERVAL_UNITS 40u
#define BLE_COURTESY_SCAN_WINDOW_UNITS 32u

#define UWB_DISCOVERY_SLOT_US MESH_RADIO_DISCOVERY_SLOT_US
#define UWB_POST_BURST_DIAG_GUARD_MS 120u
#define UWB_POST_BURST_DIAG_SLOT_MS 1000u
#define GATEWAY_BLE_RX_FRAME_QUEUE_DEPTH 4u
#define GATEWAY_BLE_DIRECT_TX_QUEUE_DEPTH 2u
#define GATEWAY_BLE_DEFAULT_NOTIFY_CHUNK 20u
#define GATEWAY_BLE_TX_RETRY_MS 2u
#define GATEWAY_BLE_TX_RETRY_MAX_MS 128u

#define MAX_SCHEDULED_ANCHORS UWB_NORMAL_CLICK_MAX_ANCHORS
#define MAX_SUCCESSFUL_ANCHORS 16u
#define WAKE_ADV_MS MESH_RADIO_WAKE_TRAIN_MS
#define ANCHOR_UWB_WAIT_MS 500u
#define UWB_DISCOVERY_RX_GUARD_MS 8u
#define UWB_DISCOVERY_RX_LATE_GUARD_MS 100u
#define UWB_DISCOVERY_LISTEN_MS \
    (UWB_DISCOVERY_RX_GUARD_MS + UWB_DISCOVERY_RX_LATE_GUARD_MS)
#define UWB_DISCOVERY_REPLY_TX_TIMEOUT_MS 20u
#define UWB_CONTROL_TX_TIMEOUT_MS 20u
#define UWB_RANGE_SCHEDULE_RX_MS 80u
#define UWB_SCHEDULE_GUARD_MS 10u
#define MESH_ROUTE_TEST_WAKE_TO_ROUTE_DELAY_MS 40u
/*
 * Sender-side single-shot wake window for the mesh route wake train: when
 * the sender's own operation decode latched the high-duty boost, the route
 * responder decoded the same flood and sits in ~100% Channel-5 RX, so one
 * WAKE_CLAIM is enough to hand over timing.  Sized to one claim TX at the
 * worst-case control-frame timeout budget plus an equal turnaround margin
 * (the same 40 ms guard MESH_ROUTE_TEST_WAKE_TO_ROUTE_DELAY_MS reserves
 * between wake and control traffic).  Unlike WAKE_ADV_MS this window does
 * not need to cover the anchor idle-scan RX-off gap pinned in main.c: a
 * boosted responder never gaps its RX.
 */
#define MESH_ROUTE_WAKE_ADV_BOOST_ACTIVE_MS \
    (UWB_CONTROL_TX_TIMEOUT_MS + UWB_CONTROL_TX_TIMEOUT_MS)
#define MESH_CONTROL_FOLLOWUP_TURNAROUND_MS \
    MESH_RADIO_EVENT_RETUNE_GUARD_MS
#define MESH_ROUTE_TEST_REPLY_WINDOW_GUARD_MS 250u
#define MESH_ROUTE_TEST_POST_WAKE_ROUTE_RX_MS 1250u
#define UWB_WAKE_CHANNEL UWB_CHANNEL_WAKE_CONTACT
#define UWB_RANGING_CHANNEL UWB_CHANNEL_WAKE_CONTACT
#define UWB_RANGE_FIRST_POLL_DELAY_MS 50u
#define UWB_SAMPLES_PER_ANCHOR 2u
#define UWB_MAX_DISCOVERY_WINDOW_MS \
    (((UWB_DISCOVERY_SLOT_COUNT * UWB_DISCOVERY_SLOT_US) + 999u) / 1000u)
#define UWB_CLICKER_MAX_SAMPLES_PER_ANCHOR UWB_RANGING_REQUESTS_MAX_PER_ANCHOR
#define UWB_DEFAULT_CLICK_MAX_EXCHANGES \
    ((UWB_RANGE_SCHEDULE_DEFAULT_BURST_WINDOW_MS * 1000u) / \
     UWB_RANGE_SCHEDULE_MIN_EXCHANGE_STRIDE_US)
/* The first range packet may carry only one diagnostic-heavy sample. */
#define ANCHOR_CLICK_RANGE_REPORT_FRAGMENT_CAPACITY \
    (1u + ((UWB_DEFAULT_CLICK_MAX_EXCHANGES - 1u + \
            RANGE_REPORT_MAX_DISTANCE_SAMPLES_FRAGMENT - 1u) / \
           RANGE_REPORT_MAX_DISTANCE_SAMPLES_FRAGMENT))
#define UWB_SCHEDULED_RANGE_SPAN_MS \
    (UWB_RANGE_FIRST_POLL_DELAY_MS + UWB_RANGE_SCHEDULE_DEFAULT_BURST_WINDOW_MS + \
     UWB_SCHEDULE_GUARD_MS)
#define UWB_POST_WAKE_CLAIMED_DURATION_MS \
    (UWB_MAX_DISCOVERY_WINDOW_MS + UWB_RANGE_SCHEDULE_RX_MS + \
     UWB_SCHEDULED_RANGE_SPAN_MS)
#define UWB_CLICKER_CLAIMED_DURATION_MS \
    (WAKE_ADV_MS + UWB_POST_WAKE_CLAIMED_DURATION_MS)
#define MAX_WAKE_ATTEMPTS 6u
#define UWB_ANCHOR_RANGE_WINDOW_MS UWB_RANGE_SCHEDULE_DEFAULT_BURST_WINDOW_MS
#define UWB_POLITE_SAMPLE_RX_MS 50u
#define UWB_POLITE_REQUIRED_QUIET_SAMPLES 2u
#define UWB_POLITE_RELEVANT_FRAME_WAIT_MS UWB_POST_WAKE_CLAIMED_DURATION_MS
#define MAX_POLITENESS_WAIT_MS 500u
#define UWB_RETRY_BASE_DELAY_MS 150u
#define BLE_COURTESY_MIN_WINDOW_MS 100u
#define BLE_COURTESY_PEER_FINISH_MS \
    (BLE_COURTESY_MIN_WINDOW_MS + UWB_CLICKER_CLAIMED_DURATION_MS)
#define BLE_COURTESY_MAX_DEFERS_PER_ATTEMPT 3u
#define CLICK_REPORT_BUILD_GUARD_MS 20u
#define CLICK_UWB_TIMEOUT_MS 40u
#define CLICK_REPORT_DEADLINE_MS 15000u
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define ANCHOR_UWB_SCAN_INTERVAL_MS CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_INTERVAL_MS
#define ANCHOR_UWB_SCAN_RX_US CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_RX_US
#define ANCHOR_UWB_SCAN_RX_MS ((CONFIG_IMEC_MESH_ROUTE_TEST_CH5_SCAN_RX_US + 999u) / 1000u)
#elif IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
#define ANCHOR_UWB_SCAN_INTERVAL_MS 0u
#define ANCHOR_UWB_SCAN_RX_US 20000u
#define ANCHOR_UWB_SCAN_RX_MS 20u
#else
#define ANCHOR_UWB_SCAN_INTERVAL_MS CONFIG_IMEC_ANCHOR_UWB_SCAN_INTERVAL_MS
#define ANCHOR_UWB_SCAN_RX_US CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US
#define ANCHOR_UWB_SCAN_RX_MS ((CONFIG_IMEC_ANCHOR_UWB_SCAN_RX_US + 999u) / 1000u)
#endif
#define ANCHOR_UWB_STARTUP_US 2500u
#define ANCHOR_UWB_PLL_US 170u
#define ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S 13000u
#define ANCHOR_UWB_IDLE_SCAN_DUTY_US ANCHOR_UWB_SCAN_RX_US
#define ANCHOR_UWB_IDLE_SCAN_AWAKE_US \
    (ANCHOR_UWB_STARTUP_US + ANCHOR_UWB_PLL_US + ANCHOR_UWB_SCAN_RX_US)
#define ANCHOR_UWB_IDLE_SCAN_PERIOD_US \
    ((ANCHOR_UWB_SCAN_INTERVAL_MS * 1000u) + ANCHOR_UWB_IDLE_SCAN_AWAKE_US)
#define ANCHOR_UWB_IDLE_SCAN_RX_OFF_GAP_US \
    ((ANCHOR_UWB_SCAN_INTERVAL_MS * 1000u) + ANCHOR_UWB_STARTUP_US + \
     ANCHOR_UWB_PLL_US)
#define ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS 60000u
#define ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS \
    ((((uint64_t)WAKE_ADV_MS * 1000ull) - ANCHOR_UWB_STARTUP_US - \
      ANCHOR_UWB_PLL_US - 1ull) / 1000ull)
#define ANCHOR_UWB_SCAN_MAX_INTERVAL_MS \
    (ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS < \
     ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS ? \
     ANCHOR_UWB_SCAN_WAKE_OVERLAP_MAX_INTERVAL_MS : \
     ANCHOR_UWB_SCAN_COMMAND_ABSOLUTE_MAX_INTERVAL_MS)
#define ANCHOR_CLAIM_COLLECTION_MS 15u
#define ANCHOR_FALSE_WAKE_COOLDOWN_MS 100u
#define ANCHOR_UWB_SCAN_ACTIVITY_COMPLETION_MS 15u
#define ANCHOR_UWB_SCAN_ACTIVITY_MIN_COMPLETION_MS 8u
#define ANCHOR_UWB_SCAN_POST_SEQUENCE_IDLE_MS 25u
#define ANCHOR_UWB_SCAN_BUSY_RETRY_MS 5u
#define ANCHOR_UWB_SCAN_MESH_RX_RETRY_MS 20u
#define ANCHOR_UWB_SCAN_DEFERRED_MESH_RX_GAP_MS 250u
#define ANCHOR_SCHEDULE_NO_POLL_GUARD_MS 5000u
#define ANCHOR_HEARTBEAT_DEFAULT_INTERVAL_MS 60000u
#define ANCHOR_HEARTBEAT_MIN_INTERVAL_MS 5000u
#define ANCHOR_HEARTBEAT_MAX_INTERVAL_MS 3600000u
#define ANCHOR_REBOOT_RESULT_DRAIN_MS 100u
#define ANCHOR_REBOOT_RESULT_POLL_MS 50u
#define ANCHOR_REBOOT_RESULT_MAX_WAIT_MS (GATEWAY_COMMAND_RESULT_TIMEOUT_MS + 500u)
#define UWB_MESH_ANCHOR_RX_INTERVAL_MS 6000u
#define UWB_MESH_ANCHOR_RX_WINDOW_MS 2u
#define ANCHOR_UWB_SCAN_MIN_INTERVAL_MS \
    ((((uint64_t)ANCHOR_UWB_IDLE_SCAN_DUTY_US * 1000000ull + \
       ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S - 1ull) / \
      ANCHOR_UWB_IDLE_RX_BUDGET_US_PER_S - \
      ANCHOR_UWB_IDLE_SCAN_DUTY_US + 999ull) / 1000ull)
#define ANCHOR_UWB_SCAN_RX_US_PER_S \
    (((uint64_t)ANCHOR_UWB_IDLE_SCAN_DUTY_US * 1000000ull + \
      ANCHOR_UWB_IDLE_SCAN_PERIOD_US - 1ull) / ANCHOR_UWB_IDLE_SCAN_PERIOD_US)
#define ANCHOR_UWB_SCAN_AWAKE_US_PER_S \
    (((uint64_t)ANCHOR_UWB_IDLE_SCAN_AWAKE_US * 1000000ull + \
      ANCHOR_UWB_IDLE_SCAN_PERIOD_US - 1ull) / ANCHOR_UWB_IDLE_SCAN_PERIOD_US)
#define ANCHOR_UWB_PERIODIC_IDLE_US_PER_S ANCHOR_UWB_SCAN_AWAKE_US_PER_S
#define UWB_MESH_GATEWAY_RX_WINDOW_MS 30000u
#define UWB_MESH_GATEWAY_RX_IDLE_MS 2u
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_EVENT_DEFAULT_INTERVAL_MS MESH_RADIO_EVENT_INTERVAL_MS
#define MESH_EVENT_DEFAULT_WINDOW_MS MESH_RADIO_EVENT_WINDOW_MS
#define MESH_EVENT_DEFAULT_FIRST_DELAY_MS MESH_RADIO_EVENT_FIRST_DELAY_MS
#define MESH_EVENT_DEFAULT_GUARD_MS MESH_RADIO_EVENT_GUARD_MS
#define MESH_EVENT_DEFAULT_SECOND_SLOT_OFFSET_MS (MESH_EVENT_DEFAULT_INTERVAL_MS / 2u)
#define MESH_EVENT_RX_LATE_GUARD_MS MESH_RADIO_EVENT_RX_LATE_GUARD_MS
#else
#define MESH_EVENT_DEFAULT_INTERVAL_MS 80u
#define MESH_EVENT_DEFAULT_WINDOW_MS 12u
#define MESH_EVENT_DEFAULT_FIRST_DELAY_MS 20u
#define MESH_EVENT_DEFAULT_GUARD_MS UWB_SCHEDULE_GUARD_MS
#define MESH_EVENT_DEFAULT_SECOND_SLOT_OFFSET_MS 0u
#define MESH_EVENT_RX_LATE_GUARD_MS 0u
#endif
#define MESH_EVENT_DEFAULT_MAX_MISSED MESH_RADIO_EVENT_MAX_MISSES
#if IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_EVENT_DEFAULT_SUPERVISION_MS MESH_RADIO_EVENT_SUPERVISION_MS
#else
#define MESH_EVENT_DEFAULT_SUPERVISION_MS 1000u
#endif
#if IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
/*
 * ML anchors use the shared channel-5 ranging scanner but never start the
 * connected-mesh RX/report workers.  Retain one fail-closed slot for any
 * unexpected legacy call without reserving production queue capacity.
 */
#define MESH_RX_QUEUE_DEPTH 1
#elif IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define MESH_RX_QUEUE_DEPTH 4
#else
#define MESH_RX_QUEUE_DEPTH 8
#endif
#if DEVICE_ROLE == ROLE_ANCHOR && IS_ENABLED(CONFIG_IMEC_ML_ANCHOR)
#define REPORT_TX_QUEUE_DEPTH 1
#elif DEVICE_ROLE == ROLE_ANCHOR && IS_ENABLED(CONFIG_IMEC_MESH_ROUTE_TEST)
#define REPORT_TX_QUEUE_DEPTH MESH_CONNECTED_ANCHOR_REPORT_QUEUE_CAPACITY
#elif DEVICE_ROLE == ROLE_ANCHOR
#define REPORT_TX_QUEUE_DEPTH 16
#else
#define REPORT_TX_QUEUE_DEPTH 1
#endif
#define REPORT_TX_RETRY_DELAY_MS 1000u
#define UWB_MESH_TX_TIMEOUT_MS 20u
BUILD_ASSERT(MESH_ENUMERATION_RELAY_SLOT_MS >=
                 UWB_CONTROL_TX_TIMEOUT_MS + 5u,
             "enumeration relay lane must fit one control TX plus margin");
BUILD_ASSERT(MESH_ENUMERATION_RELAY_COPY_GUARD_MS >=
                 UWB_CONTROL_TX_TIMEOUT_MS + 5u,
             "enumeration relay copies must not overlap one control TX");
BUILD_ASSERT(MESH_ENUMERATION_RELAY_COPY_COUNT == 3u,
             "enumeration controls must relay exactly three copies");
BUILD_ASSERT(OPERATION_POLICY_RESPONSE_TX_TIMEOUT_MS ==
                 UWB_CONTROL_TX_TIMEOUT_MS,
             "response timing model must match the control TX timeout");
#define ANCHOR_BATTERY_MV_UNKNOWN 0u
#define ANCHOR_UWB_SCAN_WORKQUEUE_STACK_SIZE 8192u
/*
 * The route-test anchor path measured 6472 bytes. Keep the full 8192-byte
 * queue for every anchor preset so the runtime
 * watermark retains the required 20 percent reserve without splitting radio
 * ownership across another worker.
 */
#define ANCHOR_UWB_SCAN_WORKQUEUE_HARDWARE_WATERMARK_BYTES 6472u
BUILD_ASSERT(ANCHOR_UWB_SCAN_WORKQUEUE_STACK_SIZE >=
             (ANCHOR_UWB_SCAN_WORKQUEUE_HARDWARE_WATERMARK_BYTES * 5u + 3u) / 4u,
             "anchor radio recovery needs measured stack plus safety margin");
#define ANCHOR_UWB_SCAN_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(1)
#define MESH_TEST_WORKQUEUE_STACK_SIZE 8192u
#define MESH_TEST_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#if IS_ENABLED(CONFIG_IMEC_DEDICATED_COMM_WORKQUEUE)
/*
 * The current clicker route owner reaches 5392 bytes synchronously; the
 * verifier's 20% free-space rule requires more than 6724 bytes, so 6784 is
 * the smallest reviewed 32-byte-aligned queue with additional rounding room.
 */
#if DEVICE_ROLE == ROLE_CLICKER
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 6784u
#elif DEVICE_ROLE == ROLE_GATEWAY
/* Survey status emission reaches a 6688-byte synchronous chain. 8384 keeps
 * the verifier's 20% free-space floor without consuming avoidable gateway
 * RAM. */
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 8384u
#else
/*
 * Four-board qualification measured 7360 bytes in the direct anchor's
 * route worker. 9472 keeps 2112 bytes free, above both the 20% policy reserve
 * (1895 bytes) and the 1024-byte application floor.
 */
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 9472u
#endif
BUILD_ASSERT(MESH_ROUTE_WORKQUEUE_STACK_SIZE >= 6784u,
             "mesh route worker needs the verified clicker stack floor");
#define MESH_ROUTE_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(0)
#else
#define MESH_ROUTE_WORKQUEUE_STACK_SIZE 4096u
#define MESH_ROUTE_WORKQUEUE_PRIORITY K_PRIO_PREEMPT(1)
#endif
#define ANCHOR_HEARTBEAT_DELIVERY_TIMEOUT_MS 60000u
#define GATEWAY_COMMAND_MESH_TIMEOUT_MARGIN_MS 1000u
#define ML_CLICKER_FAST_CACHE_MIN_ANCHORS 4u
#define ML_CLICKER_FAST_CACHE_FRESH_MS 30000u

#define UWB_POST_BURST_DIAG_RX_GUARD_MS 20u
#define UWB_POST_BURST_DIAG_TIMEOUT_MS 250u
#define UWB_POST_BURST_DIAG_ATTEMPTS 3u
#define UWB_POST_BURST_DIAG_RETRY_DELAY_MS 250u
#define UWB_POST_BURST_DIAG_REPLY_DELAY_UUS UWB_RANGE_REPLY_DELAY_UUS
#define UWB_POST_BURST_DIAG_LISTEN_MS \
    (UWB_POST_BURST_DIAG_SLOT_MS + (2u * UWB_POST_BURST_DIAG_RX_GUARD_MS))
#define UWB_POST_BURST_DIAG_ROUND_INDEX 0u
#define UWB_ML_EXCHANGE_STRIDE_US UWB_RANGE_SCHEDULE_MIN_EXCHANGE_STRIDE_US
#define UWB_ML_MAX_SCHEDULED_EXCHANGES \
    (UWB_RANGE_SCHEDULE_MAX_ANCHORS * UWB_RANGING_REQUESTS_MAX_PER_ANCHOR)
#define UWB_ML_MAX_BURST_MS \
    (((UWB_ML_MAX_SCHEDULED_EXCHANGES * UWB_ML_EXCHANGE_STRIDE_US) + 999u) / 1000u)
#define ML_CLICKER_COLLECTION_DEADLINE_MS \
    (WAKE_ADV_MS + UWB_MAX_DISCOVERY_WINDOW_MS + UWB_RANGE_SCHEDULE_RX_MS + \
     UWB_RANGE_FIRST_POLL_DELAY_MS + UWB_ML_MAX_BURST_MS + \
     UWB_POST_BURST_DIAG_GUARD_MS + \
     (UWB_RANGE_SCHEDULE_MAX_ANCHORS * UWB_POST_BURST_DIAG_SLOT_MS) + 5000u)
#define ML_CLICKER_BUFFERED_SAMPLE_MAX UWB_ML_MAX_SCHEDULED_EXCHANGES
#define ML_CLICKER_BUFFERED_FRAME_MAX 1u
#define ML_CLICKER_POST_BURST_DIAG_MAX UWB_RANGE_SCHEDULE_MAX_ANCHORS
#define UWB_FULL_CIR_REPORT_PACKET_BYTES RANGE_REPORT_CIR_PACKET_RAW_MAX_BYTES
#define ML_FULL_CIR_BLE_CHUNK_BYTES 128u
#define ML_DIAG_SOURCE_SUMMARY 0u
#define ML_DIAG_SOURCE_CLICKER 1u
#define ML_DIAG_SOURCE_ANCHOR 2u
#define ML_DIAG_SOURCE_ANCHOR_CIR 3u


#ifndef IMEC_ML_ANCHOR_SLOT
#define IMEC_ML_ANCHOR_SLOT 0u
#endif

#if defined(CONFIG_IMEC_ML_ANCHOR)
#define ANCHOR_DISCOVERY_SLOT_SOURCE "ml"
#else
#define ANCHOR_DISCOVERY_SLOT_SOURCE "gateway"
#endif

#endif
